# Generated by Django 5.2.6 on 2025-09-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('blood_group', 'Blood Group'), ('relation', 'Relation'), ('occupation', 'Occupation'), ('service', 'Service'), ('identity_type', 'Identity Type'), ('insurance_provider', 'Insurance Provider'), ('state', 'State'), ('referred_by', 'Referred By')], max_length=50)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50, unique=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('relation_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identity_no', models.CharField(blank=True, max_length=100)),
                ('insurance_no', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('biometric', models.ImageField(blank=True, null=True, upload_to='patients/biometric/')),
                ('referred_doctor', models.CharField(blank=True, max_length=100)),
                ('referred_mobile_no', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_group_options', to='app.dropdownoption')),
                ('identity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_type_options', to='app.dropdownoption')),
                ('insurance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_provider_options', to='app.dropdownoption')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_options', to='app.dropdownoption')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_options', to='app.dropdownoption')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_options', to='app.dropdownoption')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_options', to='app.dropdownoption')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_options', to='app.dropdownoption')),
            ],
        ),
    ]
