# Generated by Django 5.2.6 on 2025-09-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'blood_group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_group_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identity_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'identity_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_type_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'insurance_provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_provider_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'occupation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupation_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referred_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'referred_by'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relation',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'relation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'state'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_options', to='app.dropdownoption'),
        ),
    ]
