# Generated by Django 5.2.6 on 2025-09-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownoption',
            name='field_name',
            field=models.CharField(choices=[('blood_group', 'Blood Group'), ('relation', 'Relation'), ('occupation', 'Occupation'), ('service', 'Service'), ('identity_type', 'Identity Type'), ('insurance_provider', 'Insurance Provider'), ('state', 'State'), ('referred_by', 'Referred By'), ('nationality', 'nationality')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'nationality'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationality_options', to='app.dropdownoption'),
        ),
    ]
