# Generated by Django 5.2.6 on 2025-09-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dropdownoption_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'state'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_options', to='app.dropdownoption'),
        ),
    ]
