# Generated by Django 5.2.6 on 2025-09-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_service_alter_patient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_options', to='app.dropdownoption'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'state'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_options', to='app.dropdownoption'),
        ),
    ]
