# Generated by Django 5.2.6 on 2025-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_patient_service_alter_patient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
