# Generated by Django 5.2.6 on 2025-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_patient_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownoption',
            name='field_name',
            field=models.CharField(choices=[('blood_group', 'Blood Group'), ('relation', 'Relation'), ('occupation', 'Occupation'), ('service', 'Service'), ('identity_type', 'Identity Type'), ('insurance_provider', 'Insurance Provider'), ('state', 'State'), ('referred_doctor', 'Referred Doctor'), ('nationality', 'nationality')], max_length=50),
        ),
    ]
