# Generated by Django 5.2.6 on 2025-09-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_dropdownoption_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referred_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_name': 'referred_doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_doctor_options', to='app.dropdownoption'),
        ),
    ]
